### Importing Data and Libraries

In [69]:
import pandas as pd
import numpy as np
from scipy.stats import norm

In [70]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /opt/miniconda3/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/miniconda3/lib/python3.13/site-packages (from openpyxl) (2.0.0)

In [71]:
# Loading Prices from Excel sheet
file_name = "Base_Price.xlsx"

Price = pd.read_excel(file_name)

# Showing first few rows to verify
Price

       Segment               Product Magnet     Unit
0      PREMIUM                  750w   750w  1400000
1      PREMIUM                  HDxt     G3  1200000
2      PREMIUM                  450w   450w  1200000
3      PREMIUM                   HDi    LCC   900000
4  PERFORMANCE               Pioneer   750w  1200000
5  PERFORMANCE               Voyager   LCCw  1100000
6        VALUE  355 BRIVO/360 Optima    LCC   550000
7        VALUE     Creator - 8 Chnl.    LCC   600000
8        VALUE   Explorer - 16 Chnl.    LCC   700000

In [72]:
# Loading Actual Demand from Excel sheet
file_name = "Actual_Demand.xlsx"

Actual_Demand = pd.read_excel(file_name)

# Showing first few rows to verify
Actual_Demand.head(10)

,Segment,Product,4Q 12,1Q 13,2Q 13,3Q 13,4Q 13,1Q 14,2Q 14,3Q 14,...,3Q 15,4Q 15,1Q 16,2Q 16,3Q 16,4Q 16,1Q 17,2Q 17,Mean,Std Dev
0,PREMIUM,750w,23,31,20,32,41,0,0,0,...,3,12,22,30,28,27,26,20,16.789474,13.705550
1,PREMIUM,HDxt,9,6,6,9,9,3,9,4,...,0,0,3,1,2,0,3,1,3.894737,3.264195
2,PREMIUM,450w,71,59,56,54,78,63,64,67,...,69,76,59,69,68,72,38,50,62.263158,10.913000
3,PREMIUM,HDi,13,14,14,22,0,4,11,15,...,6,3,3,8,6,7,4,1,8.052632,5.806832
4,PERFORMANCE,Pioneer,0,0,0,0,0,0,0,0,...,6,10,12,17,14,14,14,14,5.315789,6.733438
5,PERFORMANCE,Voyager,3,7,9,10,6,8,16,15,...,20,13,14,2,3,7,12,23,10.210526,5.662537
6,VALUE,355 BRIVO/360 Optima,44,35,44,49,44,39,41,55,...,60,71,32,37,30,35,31,21,43.578947,12.902695
7,VALUE,Creator - 8 Chnl.,0,0,0,0,0,0,0,0,...,25,20,29,19,22,30,22,45,11.473684,14.249243
8,VALUE,Explorer - 16 Chnl.,0,0,0,0,0,0,0,0,...,34,29,22,33,50,30,38,0,13.000000,17.107503

In [73]:
# Loading 2 months forecast from Excel sheet
file_name = "2_month_fc.xlsx"

Two_month_fc = pd.read_excel(file_name)

# Showing first few rows to verify
Two_month_fc.head(10)

,Segment,Product,4Q 12,1Q 13,2Q 13,3Q 13,4Q 13,1Q 14,2Q 14,3Q 14,...,3Q 15,4Q 15,1Q 16,2Q 16,3Q 16,4Q 16,1Q 17,2Q 17,MSE,sqrt(MSE)
0,PREMIUM,750w,26.0,32.0,26.0,31.0,3.900000e+01,0.0,0.0,0.0,...,5,13.0,25.901099,31,32,38,29,23.0,12.011504,3.465762
1,PREMIUM,HDxt,8.0,3.0,8.0,6.0,8.000000e+00,4.0,10.0,5.0,...,1,1.0,3.000000,0,2,0,2,1.0,1.631579,1.277333
2,PREMIUM,450w,67.0,72.0,49.0,46.0,7.700000e+01,67.0,66.0,72.0,...,77,89.0,69.033529,77,73,86,47,56.0,59.930090,7.741453
3,PREMIUM,HDi,12.0,13.0,13.0,24.0,-1.000000e-10,5.0,12.0,17.0,...,4,5.0,4.000000,11,5,6,6,3.0,3.105263,1.762176
4,PERFORMANCE,Pioneer,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,6,11.0,11.901099,17,16,23,19,16.0,8.632094,2.938043
5,PERFORMANCE,Voyager,2.0,5.0,10.0,10.0,1.100000e+01,6.0,12.0,18.0,...,18,11.0,17.000000,4,3,12,18,28.0,9.947368,3.153945
6,VALUE,355 BRIVO/360 Optima,49.0,33.0,45.0,49.0,5.000000e+01,38.0,43.0,59.0,...,60,80.0,27.000000,38,31,36,33,22.0,10.894737,3.300718
7,VALUE,Creator - 8 Chnl.,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,26,30.0,36.073529,42,44,54,42,46.0,112.738675,10.617847
8,VALUE,Explorer - 16 Chnl.,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,...,34,37.0,37.703297,53,74,67,62,0.0,170.820712,13.069840

In [74]:
# Loading 6 months forecast from Excel sheet
file_name = "6_month_fc.xlsx"

Six_month_fc = pd.read_excel(file_name)

# Showing first few rows to verify
Six_month_fc.head(10)

,Segment,Product,4Q 12,1Q 13,2Q 13,3Q 13,4Q 13,1Q 14,2Q 14,3Q 14,...,3Q 15,4Q 15,1Q 16,2Q 16,3Q 16,4Q 16,1Q 17,2Q 17,MSE,sqrt(MSE)
0,PREMIUM,750w,30.0,26.0,27.0,28.0,40.0,0.0,0.0,0.0,...,5,5.0,26.0,33,33,41,29,28.0,27.421053,5.236511
1,PREMIUM,HDxt,12.0,8.0,8.0,6.0,9.0,6.0,5.0,8.0,...,1,0.0,2.0,1,2,3,1,3.0,5.473684,2.339591
2,PREMIUM,450w,65.0,66.0,69.0,72.0,78.0,74.0,71.0,76.0,...,67,73.0,56.0,56,64,83,54,60.0,100.736842,10.036774
3,PREMIUM,HDi,14.0,8.0,12.0,14.0,0.0,3.0,5.0,11.0,...,9,6.0,5.0,4,9,6,6,11.0,27.421053,5.236511
4,PERFORMANCE,Pioneer,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15,16.0,23.0,17,19,21,18,21.0,21.736842,4.662279
5,PERFORMANCE,Voyager,6.0,7.0,10.0,12.0,10.0,8.0,14.0,16.0,...,20,13.0,17.0,7,4,11,9,26.0,6.894737,2.625783
6,VALUE,355 BRIVO/360 Optima,61.0,47.0,41.0,53.0,71.0,55.0,49.0,57.0,...,70,64.0,50.0,41,32,35,26,32.0,133.421053,11.550803
7,VALUE,Creator - 8 Chnl.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16,20.0,31.0,41,42,67,54,52.0,180.842105,13.447755
8,VALUE,Explorer - 16 Chnl.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16,30.0,25.0,32,47,61,66,0.0,111.473684,10.558110

### Trimming Data

In [75]:
actual = Actual_Demand[["Segment", "Product", "Mean"]].copy()

actual = actual.rename(columns={"Mean": "mean_demand"})

actual

       Segment               Product  mean_demand
0      PREMIUM                  750w    16.789474
1      PREMIUM                  HDxt     3.894737
2      PREMIUM                  450w    62.263158
3      PREMIUM                   HDi     8.052632
4  PERFORMANCE               Pioneer     5.315789
5  PERFORMANCE               Voyager    10.210526
6        VALUE  355 BRIVO/360 Optima    43.578947
7        VALUE     Creator - 8 Chnl.    11.473684
8        VALUE   Explorer - 16 Chnl.    13.000000

In [76]:
two_m = Two_month_fc[["Segment", "Product", "sqrt(MSE)"]].copy()
two_m = two_m.rename(columns={"sqrt(MSE)": "2mo_sqrt(MSE)"})
two_m

       Segment               Product  2mo_sqrt(MSE)
0      PREMIUM                  750w       3.465762
1      PREMIUM                  HDxt       1.277333
2      PREMIUM                  450w       7.741453
3      PREMIUM                   HDi       1.762176
4  PERFORMANCE               Pioneer       2.938043
5  PERFORMANCE               Voyager       3.153945
6        VALUE  355 BRIVO/360 Optima       3.300718
7        VALUE     Creator - 8 Chnl.      10.617847
8        VALUE   Explorer - 16 Chnl.      13.069840

In [77]:
six_m = Six_month_fc[["Segment", "Product", "sqrt(MSE)"]].copy()
six_m = six_m.rename(columns={"sqrt(MSE)": "6mo_sqrt(MSE)"})
six_m

       Segment               Product  6mo_sqrt(MSE)
0      PREMIUM                  750w       5.236511
1      PREMIUM                  HDxt       2.339591
2      PREMIUM                  450w      10.036774
3      PREMIUM                   HDi       5.236511
4  PERFORMANCE               Pioneer       4.662279
5  PERFORMANCE               Voyager       2.625783
6        VALUE  355 BRIVO/360 Optima      11.550803
7        VALUE     Creator - 8 Chnl.      13.447755
8        VALUE   Explorer - 16 Chnl.      10.558110

In [78]:
# Megre into a single table

df = actual.merge(two_m, on=["Segment", "Product"], how="inner")
df = df.merge(six_m, on=["Segment", "Product"], how="inner")

df

,Segment,Product,mean_demand,2mo_sqrt(MSE),6mo_sqrt(MSE)
0,PREMIUM,750w,16.789474,3.465762,5.236511
1,PREMIUM,HDxt,3.894737,1.277333,2.339591
2,PREMIUM,450w,62.263158,7.741453,10.036774
3,PREMIUM,HDi,8.052632,1.762176,5.236511
4,PERFORMANCE,Pioneer,5.315789,2.938043,4.662279
5,PERFORMANCE,Voyager,10.210526,3.153945,2.625783
6,VALUE,355 BRIVO/360 Optima,43.578947,3.300718,11.550803
7,VALUE,Creator - 8 Chnl.,11.473684,10.617847,13.447755
8,VALUE,Explorer - 16 Chnl.,13.000000,13.069840,10.558110

### Newsvendor model

In [79]:
# Defining underage and overage costs and critical ratio

underage_cost = 0.20   # profit from selling one extra unit = 20% of wholesale price
overage_cost = 0.065   # loss from one extra unsold unit = 6.5% of wholesale price

critical_fractile = underage_cost / (underage_cost + overage_cost)
z_value = norm.ppf(critical_fractile)

print("Critical fractile:", critical_fractile)
print("Z-value:", z_value)

Critical fractile: 0.7547169811320755
Z-value: 0.6894088149784472

In [80]:
df["Q_star_2m"] = df["mean_demand"] + z_value * df["2mo_sqrt(MSE)"]
df["Q_star_6m"] = df["mean_demand"] + z_value * df["6mo_sqrt(MSE)"]

# Since MRI machines are whole units, round up to the next integer
df["Q_star_2m"] = np.ceil(df["Q_star_2m"]).astype(int)
df["Q_star_6m"] = np.ceil(df["Q_star_6m"]).astype(int)

print(df[["Segment", "Product", "mean_demand", "2mo_sqrt(MSE)", "6mo_sqrt(MSE)", "Q_star_2m", "Q_star_6m"]])

       Segment               Product  mean_demand  2mo_sqrt(MSE)  \
0      PREMIUM                  750w    16.789474       3.465762
1      PREMIUM                  HDxt     3.894737       1.277333
2      PREMIUM                  450w    62.263158       7.741453
3      PREMIUM                   HDi     8.052632       1.762176
4  PERFORMANCE               Pioneer     5.315789       2.938043
5  PERFORMANCE               Voyager    10.210526       3.153945
6        VALUE  355 BRIVO/360 Optima    43.578947       3.300718
7        VALUE     Creator - 8 Chnl.    11.473684      10.617847
8        VALUE   Explorer - 16 Chnl.    13.000000      13.069840

   6mo_sqrt(MSE)  Q_star_2m  Q_star_6m
0       5.236511         20         21
1       2.339591          5          6
2      10.036774         68         70
3       5.236511         10         12
4       4.662279          8          9
5       2.625783         13         13
6      11.550803         46         52
7      13.447755         19         21
8      10.558110         23         21

### Calculating profits

In [83]:
# Keeping only the price columns we need
price = Price[["Segment", "Product", "Unit"]].copy()

# Merging prices with quantity data
df = df.merge(price, on=["Segment", "Product"], how="inner")

# Check result
print(df[["Segment", "Product", "mean_demand", "Q_star_2m", "Q_star_6m", "2mo_sqrt(MSE)", "6mo_sqrt(MSE)", "Unit"]])

       Segment               Product  mean_demand  Q_star_2m  Q_star_6m  \
0      PREMIUM                  750w    16.789474         20         21
1      PREMIUM                  HDxt     3.894737          5          6
2      PREMIUM                  450w    62.263158         68         70
3      PREMIUM                   HDi     8.052632         10         12
4  PERFORMANCE               Pioneer     5.315789          8          9
5  PERFORMANCE               Voyager    10.210526         13         13
6        VALUE  355 BRIVO/360 Optima    43.578947         46         52
7        VALUE     Creator - 8 Chnl.    11.473684         19         21
8        VALUE   Explorer - 16 Chnl.    13.000000         23         21

   2mo_sqrt(MSE)  6mo_sqrt(MSE)     Unit
0       3.465762       5.236511  1400000
1       1.277333       2.339591  1200000
2       7.741453      10.036774  1200000
3       1.762176       5.236511   900000
4       2.938043       4.662279  1200000
5       3.153945       2.625783  1100000
6       3.300718      11.550803   550000
7      10.617847      13.447755   600000
8      13.069840      10.558110   700000

In [84]:
# Definining underage and overage costs as actual costs (instead of a % of price)

underage_rate = 0.20   # profit on one sold unit
overage_rate = 0.065   # loss on one leftover unit

df["profit_per_sold_unit"] = underage_rate * df["Unit"]
df["loss_per_leftover_unit"] = overage_rate * df["Unit"]

print(df[["Segment", "Product", "Unit", "profit_per_sold_unit", "loss_per_leftover_unit"]])

       Segment               Product     Unit  profit_per_sold_unit  \
0      PREMIUM                  750w  1400000              280000.0
1      PREMIUM                  HDxt  1200000              240000.0
2      PREMIUM                  450w  1200000              240000.0
3      PREMIUM                   HDi   900000              180000.0
4  PERFORMANCE               Pioneer  1200000              240000.0
5  PERFORMANCE               Voyager  1100000              220000.0
6        VALUE  355 BRIVO/360 Optima   550000              110000.0
7        VALUE     Creator - 8 Chnl.   600000              120000.0
8        VALUE   Explorer - 16 Chnl.   700000              140000.0

   loss_per_leftover_unit
0                 91000.0
1                 78000.0
2                 78000.0
3                 58500.0
4                 78000.0
5                 71500.0
6                 35750.0
7                 39000.0
8                 45500.0

In [85]:
# Calculating sold and leftover units

# 2-month scenario
df["expected_sold_2m"] = np.minimum(df["Q_star_2m"], df["mean_demand"])
df["expected_leftover_2m"] = np.maximum(df["Q_star_2m"] - df["mean_demand"], 0)

# 6-month scenario
df["expected_sold_6m"] = np.minimum(df["Q_star_6m"], df["mean_demand"])
df["expected_leftover_6m"] = np.maximum(df["Q_star_6m"] - df["mean_demand"], 0)

print(df[[
    "Segment", "Product", "mean_demand",
    "Q_star_2m", "expected_sold_2m", "expected_leftover_2m",
    "Q_star_6m", "expected_sold_6m", "expected_leftover_6m"
]])

       Segment               Product  mean_demand  Q_star_2m  \
0      PREMIUM                  750w    16.789474         20
1      PREMIUM                  HDxt     3.894737          5
2      PREMIUM                  450w    62.263158         68
3      PREMIUM                   HDi     8.052632         10
4  PERFORMANCE               Pioneer     5.315789          8
5  PERFORMANCE               Voyager    10.210526         13
6        VALUE  355 BRIVO/360 Optima    43.578947         46
7        VALUE     Creator - 8 Chnl.    11.473684         19
8        VALUE   Explorer - 16 Chnl.    13.000000         23

   expected_sold_2m  expected_leftover_2m  Q_star_6m  expected_sold_6m  \
0         16.789474              3.210526         21         16.789474
1          3.894737              1.105263          6          3.894737
2         62.263158              5.736842         70         62.263158
3          8.052632              1.947368         12          8.052632
4          5.315789              2.684211          9          5.315789
5         10.210526              2.789474         13         10.210526
6         43.578947              2.421053         52         43.578947
7         11.473684              7.526316         21         11.473684
8         13.000000             10.000000         21         13.000000

   expected_leftover_6m
0              4.210526
1              2.105263
2              7.736842
3              3.947368
4              3.684211
5              2.789474
6              8.421053
7              9.526316
8              8.000000

In [89]:
#Calculating expected profits

# 2-month expected profit
df["expected_profit_2m"] = (
    df["expected_sold_2m"] * df["profit_per_sold_unit"]
    - df["expected_leftover_2m"] * df["loss_per_leftover_unit"]
)

# 6-month expected profit
df["expected_profit_6m"] = (
    df["expected_sold_6m"] * df["profit_per_sold_unit"]
    - df["expected_leftover_6m"] * df["loss_per_leftover_unit"]
)

df[[
    "Segment", "Product",
    "expected_profit_2m", "expected_profit_6m"
]]

       Segment               Product  expected_profit_2m  expected_profit_6m
0      PREMIUM                  750w        4.408895e+06        4.317895e+06
1      PREMIUM                  HDxt        8.485263e+05        7.705263e+05
2      PREMIUM                  450w        1.449568e+07        1.433968e+07
3      PREMIUM                   HDi        1.335553e+06        1.218553e+06
4  PERFORMANCE               Pioneer        1.066421e+06        9.884211e+05
5  PERFORMANCE               Voyager        2.046868e+06        2.046868e+06
6        VALUE  355 BRIVO/360 Optima        4.707132e+06        4.492632e+06
7        VALUE     Creator - 8 Chnl.        1.083316e+06        1.005316e+06
8        VALUE   Explorer - 16 Chnl.        1.365000e+06        1.456000e+06

In [92]:
# Compare twwo months vs 6 months

df["profit_difference"] = df["expected_profit_2m"] - df["expected_profit_6m"]
df["Q_difference"] = df["Q_star_6m"] - df["Q_star_2m"]

df["better_scenario"] = np.where(
    df["expected_profit_2m"] > df["expected_profit_6m"],
    "2-month",
    "6-month"
)

comparison = df[[
    "Segment",
    "Product",
    "mean_demand",
    "2mo_sqrt(MSE)",
    "6mo_sqrt(MSE)",
    "Q_star_2m",
    "Q_star_6m",
    "expected_profit_2m",
    "expected_profit_6m",
    "profit_difference",
    "Q_difference",
    "better_scenario"
]]

comparison

,Segment,Product,mean_demand,2mo_sqrt(MSE),6mo_sqrt(MSE),Q_star_2m,Q_star_6m,expected_profit_2m,expected_profit_6m,profit_difference,Q_difference,better_scenario
0,PREMIUM,750w,16.789474,3.465762,5.236511,20,21,4.408895e+06,4.317895e+06,91000.0,1,2-month
1,PREMIUM,HDxt,3.894737,1.277333,2.339591,5,6,8.485263e+05,7.705263e+05,78000.0,1,2-month
2,PREMIUM,450w,62.263158,7.741453,10.036774,68,70,1.449568e+07,1.433968e+07,156000.0,2,2-month
3,PREMIUM,HDi,8.052632,1.762176,5.236511,10,12,1.335553e+06,1.218553e+06,117000.0,2,2-month
4,PERFORMANCE,Pioneer,5.315789,2.938043,4.662279,8,9,1.066421e+06,9.884211e+05,78000.0,1,2-month
5,PERFORMANCE,Voyager,10.210526,3.153945,2.625783,13,13,2.046868e+06,2.046868e+06,0.0,0,6-month
6,VALUE,355 BRIVO/360 Optima,43.578947,3.300718,11.550803,46,52,4.707132e+06,4.492632e+06,214500.0,6,2-month
7,VALUE,Creator - 8 Chnl.,11.473684,10.617847,13.447755,19,21,1.083316e+06,1.005316e+06,78000.0,2,2-month
8,VALUE,Explorer - 16 Chnl.,13.000000,13.069840,10.558110,23,21,1.365000e+06,1.456000e+06,-91000.0,-2,6-month

In [95]:
# Rounding for readability
comparison_rounded = comparison.copy()

comparison_rounded["expected_profit_2m"] = comparison_rounded["expected_profit_2m"].round(2)
comparison_rounded["expected_profit_6m"] = comparison_rounded["expected_profit_6m"].round(2)
comparison_rounded["profit_difference"] = comparison_rounded["profit_difference"].round(2)
comparison_rounded["mean_demand"] = comparison_rounded["mean_demand"].round(2)
comparison_rounded["2mo_sqrt(MSE)"] = comparison_rounded["2mo_sqrt(MSE)"].round(2)
comparison_rounded["6mo_sqrt(MSE)"] = comparison_rounded["6mo_sqrt(MSE)"].round(2)

comparison_rounded

,Segment,Product,mean_demand,2mo_sqrt(MSE),6mo_sqrt(MSE),Q_star_2m,Q_star_6m,expected_profit_2m,expected_profit_6m,profit_difference,Q_difference,better_scenario
0,PREMIUM,750w,16.79,3.47,5.24,20,21,4408894.74,4317894.74,91000.0,1,2-month
1,PREMIUM,HDxt,3.89,1.28,2.34,5,6,848526.32,770526.32,78000.0,1,2-month
2,PREMIUM,450w,62.26,7.74,10.04,68,70,14495684.21,14339684.21,156000.0,2,2-month
3,PREMIUM,HDi,8.05,1.76,5.24,10,12,1335552.63,1218552.63,117000.0,2,2-month
4,PERFORMANCE,Pioneer,5.32,2.94,4.66,8,9,1066421.05,988421.05,78000.0,1,2-month
5,PERFORMANCE,Voyager,10.21,3.15,2.63,13,13,2046868.42,2046868.42,0.0,0,6-month
6,VALUE,355 BRIVO/360 Optima,43.58,3.30,11.55,46,52,4707131.58,4492631.58,214500.0,6,2-month
7,VALUE,Creator - 8 Chnl.,11.47,10.62,13.45,19,21,1083315.79,1005315.79,78000.0,2,2-month
8,VALUE,Explorer - 16 Chnl.,13.00,13.07,10.56,23,21,1365000.00,1456000.00,-91000.0,-2,6-month

In [96]:
comparison_rounded.to_excel("newsvendor_expected_profit_results.xlsx", index=False)